version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=Asia/Singapore"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5433:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"